# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/deep_merge/all/deep_merge.rbi
#
# deep_merge-1.2.2

module DeepMerge
  def self.clear_or_nil(obj); end
  def self.deep_merge!(source, dest, options = nil); end
  def self.overwrite_unmergeables(source, dest, options); end
end
class DeepMerge::InvalidParameter < StandardError
end
module DeepMerge::DeepMergeHash
  def deep_merge!(source, options = nil); end
  def deep_merge(source, options = nil); end
  def ko_deep_merge!(source, options = nil); end
end
class Hash
  include DeepMerge::DeepMergeHash
end
