# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flutter/all/flutter.rbi
#
# flutter-0.2.4

module Minitest
  def self.plugin_flutter_init(options); end
end
