# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/guard-minitest/all/guard-minitest.rbi
#
# guard-minitest-2.4.6

module Minitest
  def self.plugin_guard_minitest_init(options); end
  def self.plugin_guard_minitest_options(opts, options); end
end
