# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mustermann-grape/all/mustermann-grape.rbi
#
# mustermann-grape-1.0.2

module Mustermann
end
class Mustermann::Grape < Mustermann::AST::Pattern
end
class Mustermann::Grape::Parser < Mustermann::AST::Parser
end
