# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-accept/all/rack-accept.rbi
#
# rack-accept-0.4.5

module Rack::Accept
  def self.new(app, &block); end
end
