# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack/all/rack.rbi
#
# rack-3.0.0

module Rack
  def self.release; end
  def self.version; end
end
class Rack::BodyProxy
  def close; end
  def closed?; end
  def initialize(body, &block); end
  def method_missing(method_name, *args, &block); end
  def respond_to_missing?(method_name, include_all = nil); end
end
class Rack::QueryParser
  def _normalize_params(params, name, v, depth); end
  def initialize(params_class, _key_space_limit = nil, param_depth_limit); end
  def make_params; end
  def new_depth_limit(param_depth_limit); end
  def normalize_params(params, name, v, _depth = nil); end
  def param_depth_limit; end
  def params_hash_has_key?(hash, key); end
  def params_hash_type?(obj); end
  def parse_nested_query(qs, separator = nil); end
  def parse_query(qs, separator = nil, &unescaper); end
  def self.make_default(_key_space_limit = nil, param_depth_limit); end
  def unescape(s); end
end
class Rack::QueryParser::ParameterTypeError < TypeError
end
class Rack::QueryParser::InvalidParameterError < ArgumentError
end
class Rack::QueryParser::ParamsTooDeepError < RangeError
end
class Rack::QueryParser::Params
  def [](key); end
  def []=(key, value); end
  def initialize; end
  def key?(key); end
  def to_h; end
  def to_params_hash; end
end
module Rack::Mime
  def match?(value, matcher); end
  def mime_type(ext, fallback = nil); end
  def self.match?(value, matcher); end
  def self.mime_type(ext, fallback = nil); end
end
class Rack::Headers < Hash
  def [](key); end
  def []=(key, value); end
  def assoc(key); end
  def compare_by_identity; end
  def delete(key); end
  def dig(key, *a); end
  def downcase_key(key); end
  def fetch(key, *default, &block); end
  def fetch_values(*a); end
  def has_key?(key); end
  def include?(key); end
  def invert; end
  def key?(key); end
  def member?(key); end
  def merge!(hash, &block); end
  def merge(hash, &block); end
  def reject(&block); end
  def replace(hash); end
  def select(&block); end
  def self.[](*items); end
  def slice(*a); end
  def store(key, value); end
  def to_proc; end
  def transform_keys!; end
  def transform_keys(&block); end
  def transform_values(&block); end
  def update(hash, &block); end
  def values_at(*keys); end
end
module Rack::Utils
  def add_cookie_to_header(header, key, value); end
  def add_remove_cookie_to_header(header, key, value = nil); end
  def best_q_match(q_value_header, available_mimes); end
  def build_nested_query(value, prefix = nil); end
  def build_query(params); end
  def byte_ranges(env, size); end
  def clean_path_info(path_info); end
  def clock_time; end
  def delete_cookie_header!(headers, key, value = nil); end
  def delete_set_cookie_header!(header, key, value = nil); end
  def delete_set_cookie_header(key, value = nil); end
  def escape(s); end
  def escape_html(string); end
  def escape_path(s); end
  def forwarded_values(forwarded_header); end
  def get_byte_ranges(http_range, size); end
  def make_delete_cookie_header(header, key, value); end
  def parse_cookies(env); end
  def parse_cookies_header(value); end
  def parse_nested_query(qs, d = nil); end
  def parse_query(qs, d = nil, &unescaper); end
  def q_values(q_value_header); end
  def rfc2822(time); end
  def secure_compare(a, b); end
  def select_best_encoding(available_encodings, accept_encoding); end
  def self.add_cookie_to_header(header, key, value); end
  def self.add_remove_cookie_to_header(header, key, value = nil); end
  def self.best_q_match(q_value_header, available_mimes); end
  def self.build_nested_query(value, prefix = nil); end
  def self.build_query(params); end
  def self.byte_ranges(env, size); end
  def self.clean_path_info(path_info); end
  def self.clock_time; end
  def self.default_query_parser; end
  def self.default_query_parser=(arg0); end
  def self.delete_cookie_header!(headers, key, value = nil); end
  def self.delete_set_cookie_header!(header, key, value = nil); end
  def self.delete_set_cookie_header(key, value = nil); end
  def self.escape(s); end
  def self.escape_html(string); end
  def self.escape_path(s); end
  def self.forwarded_values(forwarded_header); end
  def self.get_byte_ranges(http_range, size); end
  def self.key_space_limit; end
  def self.key_space_limit=(v); end
  def self.make_delete_cookie_header(header, key, value); end
  def self.multipart_part_limit; end
  def self.multipart_part_limit=(arg0); end
  def self.param_depth_limit; end
  def self.param_depth_limit=(v); end
  def self.parse_cookies(env); end
  def self.parse_cookies_header(value); end
  def self.parse_nested_query(qs, d = nil); end
  def self.parse_query(qs, d = nil, &unescaper); end
  def self.q_values(q_value_header); end
  def self.rfc2822(time); end
  def self.secure_compare(a, b); end
  def self.select_best_encoding(available_encodings, accept_encoding); end
  def self.set_cookie_header!(headers, key, value); end
  def self.set_cookie_header(key, value); end
  def self.status_code(status); end
  def self.unescape(s, encoding = nil); end
  def self.unescape_path(s); end
  def self.valid_path?(path); end
  def set_cookie_header!(headers, key, value); end
  def set_cookie_header(key, value); end
  def status_code(status); end
  def unescape(s, encoding = nil); end
  def unescape_path(s); end
  def valid_path?(path); end
end
class Rack::Utils::Context
  def app; end
  def call(env); end
  def context(env, app = nil); end
  def for; end
  def initialize(app_f, app_r); end
  def recontext(app); end
end
class Rack::Utils::HeaderHash < Hash
  def self.[](headers); end
  def self.allocate; end
  def self.new(hash = nil); end
end
module Rack::Auth
end
class Rack::URLMap
  def call(env); end
  def casecmp?(v1, v2); end
  def initialize(map = nil); end
  def remap(map); end
end
class Rack::Builder
  def call(env); end
  def freeze_app; end
  def generate_map(default_app, mapping); end
  def initialize(default_app = nil, &block); end
  def map(path, &block); end
  def run(app = nil, &block); end
  def self.app(default_app = nil, &block); end
  def self.load_file(path); end
  def self.new_from_string(builder_script, file = nil); end
  def self.parse_file(path); end
  def to_app; end
  def use(middleware, *args, &block); end
  def warmup(prc = nil, &block); end
end
class Rack::Auth::AbstractHandler
  def bad_request; end
  def initialize(app, realm = nil, &authenticator); end
  def realm; end
  def realm=(arg0); end
  def unauthorized(www_authenticate = nil); end
end
class Rack::MediaType
  def self.params(content_type); end
  def self.strip_doublequotes(str); end
  def self.type(content_type); end
end
class Rack::Request
  def delete_param(k); end
  def initialize(env); end
  def params; end
  def self.forwarded_priority; end
  def self.forwarded_priority=(arg0); end
  def self.ip_filter; end
  def self.ip_filter=(arg0); end
  def self.x_forwarded_proto_priority; end
  def self.x_forwarded_proto_priority=(arg0); end
  def update_param(k, v); end
  include Rack::Request::Env
  include Rack::Request::Helpers
end
module Rack::Request::Env
  def add_header(key, v); end
  def delete_header(name); end
  def each_header(&block); end
  def env; end
  def fetch_header(name, &block); end
  def get_header(name); end
  def has_header?(name); end
  def initialize(env); end
  def initialize_copy(other); end
  def set_header(name, v); end
end
module Rack::Request::Helpers
  def GET; end
  def POST; end
  def [](key); end
  def []=(key, value); end
  def accept_encoding; end
  def accept_language; end
  def allowed_scheme(header); end
  def authority; end
  def base_url; end
  def body; end
  def content_charset; end
  def content_length; end
  def content_type; end
  def cookies; end
  def default_session; end
  def delete?; end
  def delete_param(k); end
  def form_data?; end
  def forwarded_authority; end
  def forwarded_for; end
  def forwarded_port; end
  def forwarded_priority; end
  def forwarded_scheme; end
  def fullpath; end
  def get?; end
  def get_http_forwarded(token); end
  def head?; end
  def host; end
  def host_authority; end
  def host_with_port(authority = nil); end
  def hostname; end
  def ip; end
  def link?; end
  def logger; end
  def media_type; end
  def media_type_params; end
  def options?; end
  def params; end
  def parse_http_accept_header(header); end
  def parse_multipart; end
  def parse_query(qs, d = nil); end
  def parseable_data?; end
  def patch?; end
  def path; end
  def path_info; end
  def path_info=(s); end
  def port; end
  def post?; end
  def put?; end
  def query_parser; end
  def query_string; end
  def referer; end
  def referrer; end
  def reject_trusted_ip_addresses(ip_addresses); end
  def request_method; end
  def scheme; end
  def script_name; end
  def script_name=(s); end
  def server_authority; end
  def server_name; end
  def server_port; end
  def session; end
  def session_options; end
  def split_authority(authority); end
  def split_header(value); end
  def ssl?; end
  def trace?; end
  def trusted_proxy?(ip); end
  def unlink?; end
  def update_param(k, v); end
  def url; end
  def user_agent; end
  def values_at(*keys); end
  def wrap_ipv6(host); end
  def x_forwarded_proto_priority; end
  def xhr?; end
end
class Rack::Auth::AbstractRequest
  def authorization_key; end
  def initialize(env); end
  def params; end
  def parts; end
  def provided?; end
  def request; end
  def scheme; end
  def valid?; end
end
class Rack::Auth::Basic < Rack::Auth::AbstractHandler
  def call(env); end
  def challenge; end
  def valid?(auth); end
end
class Rack::Auth::Basic::Request < Rack::Auth::AbstractRequest
  def basic?; end
  def credentials; end
  def username; end
end
module Rack::Auth::Digest
end
class Rack::Auth::Digest::Nonce
  def digest; end
  def fresh?; end
  def initialize(timestamp = nil, given_digest = nil); end
  def self.parse(string); end
  def self.private_key; end
  def self.private_key=(arg0); end
  def self.time_limit; end
  def self.time_limit=(arg0); end
  def stale?; end
  def to_s; end
  def valid?; end
end
class Rack::Auth::Digest::Params < Hash
  def [](k); end
  def []=(k, v); end
  def initialize; end
  def quote(str); end
  def self.dequote(str); end
  def self.parse(str); end
  def self.split_header_value(str); end
  def to_s; end
end
class Rack::Auth::Digest::Request < Rack::Auth::AbstractRequest
  def correct_uri?; end
  def digest?; end
  def method; end
  def method_missing(sym, *args); end
  def nonce; end
  def params; end
  def respond_to?(sym, *arg1); end
end
class Rack::Auth::Digest::MD5 < Rack::Auth::AbstractHandler
  def A1(auth, password); end
  def A2(auth); end
  def H(data); end
  def KD(secret, data); end
  def call(env); end
  def challenge(hash = nil); end
  def digest(auth, password); end
  def initialize(app, realm = nil, opaque = nil, &authenticator); end
  def md5(data); end
  def opaque; end
  def opaque=(arg0); end
  def params(hash = nil); end
  def passwords_hashed=(arg0); end
  def passwords_hashed?; end
  def valid?(auth); end
  def valid_digest?(auth); end
  def valid_nonce?(auth); end
  def valid_opaque?(auth); end
  def valid_qop?(auth); end
end
module Rack::Multipart
  def self.build_multipart(params, first = nil); end
  def self.extract_multipart(request, params = nil); end
  def self.parse_multipart(env, params = nil); end
end
class Rack::Multipart::MultipartPartLimitError < Errno::EMFILE
end
class Rack::Multipart::EmptyContentError < EOFError
end
class Rack::Multipart::Error < StandardError
end
class Rack::Multipart::Parser
  def consume_boundary; end
  def dequote(str); end
  def get_filename(head); end
  def handle_consume_token; end
  def handle_empty_content!(content); end
  def handle_fast_forward; end
  def handle_mime_body; end
  def handle_mime_head; end
  def initialize(boundary, tempfile, bufsize, query_parser); end
  def parse(io); end
  def read_data(io, outbuf); end
  def result; end
  def self.parse(io, content_length, content_type, tmpfile, bufsize, qp); end
  def self.parse_boundary(content_type); end
  def state; end
  def tag_multipart_encoding(filename, content_type, name, body); end
end
class Rack::Multipart::Parser::BoundedIO
  def initialize(io, content_length); end
  def read(size, outbuf = nil); end
end
class Rack::Multipart::Parser::MultipartInfo < Struct
  def params; end
  def params=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tmp_files; end
  def tmp_files=(_); end
end
class Rack::Multipart::Parser::Collector
  def check_open_files; end
  def each; end
  def initialize(tempfile); end
  def on_mime_body(mime_index, content); end
  def on_mime_finish(mime_index); end
  def on_mime_head(mime_index, head, filename, content_type, name); end
  include Enumerable
end
class Anonymous_Struct_1 < Struct
  def body; end
  def body=(_); end
  def content_type; end
  def content_type=(_); end
  def filename; end
  def filename=(_); end
  def head; end
  def head=(_); end
  def name; end
  def name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Rack::Multipart::Parser::Collector::MimePart < Anonymous_Struct_1
  def get_data; end
end
class Rack::Multipart::Parser::Collector::BufferPart < Rack::Multipart::Parser::Collector::MimePart
  def close; end
  def file?; end
end
class Rack::Multipart::Parser::Collector::TempfilePart < Rack::Multipart::Parser::Collector::MimePart
  def close; end
  def file?; end
end
class Rack::Multipart::UploadedFile
  def content_type; end
  def content_type=(arg0); end
  def initialize(filepath = nil, ct = nil, bin = nil, path: nil, content_type: nil, binary: nil, filename: nil, io: nil); end
  def local_path; end
  def method_missing(method_name, *args, &block); end
  def original_filename; end
  def path; end
  def respond_to?(*args); end
end
class Rack::Multipart::Generator
  def content_for_other(file, name); end
  def content_for_tempfile(io, file, name); end
  def dump; end
  def flattened_params; end
  def initialize(params, first = nil); end
  def multipart?; end
end
class Rack::Cascade
  def <<(app); end
  def add(app); end
  def apps; end
  def call(env); end
  def include?(app); end
  def initialize(apps, cascade_for = nil); end
end
class Rack::Chunked
  def call(env); end
  def chunkable_version?(ver); end
  def initialize(app); end
  include Rack::Utils
end
class Rack::Chunked::Body
  def close; end
  def each(&block); end
  def initialize(body); end
  def yield_trailers; end
end
class Rack::Chunked::TrailerBody < Rack::Chunked::Body
  def yield_trailers; end
end
class Rack::CommonLogger
  def call(env); end
  def extract_content_length(headers); end
  def initialize(app, logger = nil); end
  def log(env, status, response_headers, began_at); end
end
class Rack::ConditionalGet
  def call(env); end
  def etag_matches?(none_match, headers); end
  def fresh?(env, headers); end
  def initialize(app); end
  def modified_since?(modified_since, headers); end
  def to_rfc2822(since); end
end
class Rack::Config
  def call(env); end
  def initialize(app, &block); end
end
class Rack::ContentLength
  def call(env); end
  def initialize(app); end
  include Rack::Utils
end
class Rack::ContentType
  def call(env); end
  def initialize(app, content_type = nil); end
  include Rack::Utils
end
class Rack::ETag
  def call(env); end
  def digest_body(body); end
  def etag_status?(status); end
  def initialize(app, no_cache_control = nil, cache_control = nil); end
  def skip_caching?(headers); end
end
class Rack::Response
  def [](key); end
  def []=(key, value); end
  def body; end
  def body=(arg0); end
  def chunked?; end
  def close; end
  def delete_header(key); end
  def each(&callback); end
  def empty?; end
  def finish(&block); end
  def get_header(key); end
  def has_header?(key); end
  def header; end
  def headers; end
  def initialize(body = nil, status = nil, headers = nil); end
  def length; end
  def length=(arg0); end
  def redirect(target, status = nil); end
  def self.[](status, headers, body); end
  def set_header(key, value); end
  def status; end
  def status=(arg0); end
  def to_a(&block); end
  def write(chunk); end
  include Rack::Response::Helpers
end
module Rack::Response::Helpers
  def accepted?; end
  def add_header(key, value); end
  def append(chunk); end
  def bad_request?; end
  def buffered_body!; end
  def cache!(duration = nil, directive: nil); end
  def cache_control; end
  def cache_control=(value); end
  def client_error?; end
  def content_length; end
  def content_type; end
  def content_type=(content_type); end
  def created?; end
  def delete_cookie(key, value = nil); end
  def do_not_cache!; end
  def etag; end
  def etag=(value); end
  def forbidden?; end
  def include?(header); end
  def informational?; end
  def invalid?; end
  def location; end
  def location=(location); end
  def media_type; end
  def media_type_params; end
  def method_not_allowed?; end
  def moved_permanently?; end
  def no_content?; end
  def not_acceptable?; end
  def not_found?; end
  def ok?; end
  def precondition_failed?; end
  def redirect?; end
  def redirection?; end
  def request_timeout?; end
  def server_error?; end
  def set_cookie(key, value); end
  def set_cookie_header; end
  def set_cookie_header=(value); end
  def successful?; end
  def unauthorized?; end
  def unprocessable?; end
end
class Rack::Response::Raw
  def delete_header(key); end
  def get_header(key); end
  def has_header?(key); end
  def headers; end
  def initialize(status, headers); end
  def set_header(key, value); end
  def status; end
  def status=(arg0); end
  include Rack::Response::Helpers
end
class Rack::Events
  def call(env); end
  def initialize(app, handlers); end
  def make_request(env); end
  def make_response(status, headers, body); end
  def on_commit(request, response); end
  def on_error(request, response, e); end
  def on_finish(request, response); end
  def on_start(request, response); end
end
module Rack::Events::Abstract
  def on_commit(req, res); end
  def on_error(req, res, e); end
  def on_finish(req, res); end
  def on_send(req, res); end
  def on_start(req, res); end
end
class Rack::Events::EventedBodyProxy < Rack::BodyProxy
  def each; end
  def initialize(body, request, response, handlers, &block); end
  def request; end
  def response; end
end
class Rack::Events::BufferedResponse < Rack::Response::Raw
  def body; end
  def initialize(status, headers, body); end
  def to_a; end
end
class Rack::Head
  def call(env); end
  def initialize(app); end
end
class Rack::Files
  def call(env); end
  def fail(status, body, headers = nil); end
  def filesize(path); end
  def get(env); end
  def initialize(root, headers = nil, default_mime = nil); end
  def mime_type(path, default_mime); end
  def root; end
  def serving(request, path); end
end
class Rack::Files::BaseIterator
  def bytesize; end
  def close; end
  def each; end
  def each_range_part(file, range); end
  def initialize(path, ranges, options); end
  def multipart?; end
  def multipart_heading(range); end
  def options; end
  def path; end
  def ranges; end
end
class Rack::Files::Iterator < Rack::Files::BaseIterator
  def to_path; end
end
class Rack::Deflater
  def call(env); end
  def initialize(app, options = nil); end
  def should_deflate?(env, status, headers, body); end
end
class Rack::Deflater::GzipStream
  def close; end
  def each(&block); end
  def initialize(body, mtime, sync); end
  def write(data); end
end
class Rack::Directory
  def call(env); end
  def check_bad_request(path_info); end
  def check_forbidden(path_info); end
  def entity_not_found(path_info); end
  def filesize_format(int); end
  def get(env); end
  def initialize(root, app = nil); end
  def list_directory(path_info, path, script_name); end
  def list_path(env, path, path_info, script_name); end
  def root; end
  def stat(path); end
end
class Anonymous_Struct_2 < Struct
  def files; end
  def files=(_); end
  def path; end
  def path=(_); end
  def root; end
  def root=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Rack::Directory::DirectoryBody < Anonymous_Struct_2
  def DIR_FILE_escape(htmls); end
  def each; end
end
class Rack::ForwardRequest < Exception
  def env; end
  def initialize(url, env = nil); end
  def url; end
end
class Rack::Recursive
  def _call(env); end
  def call(env); end
  def include(env, path); end
  def initialize(app); end
end
class Rack::MockResponse < Rack::Response
  def =~(other); end
  def body; end
  def cookie(name); end
  def cookies; end
  def empty?; end
  def errors; end
  def errors=(arg0); end
  def identify_cookie_attributes(cookie_filling); end
  def initialize(status, headers, body, errors = nil); end
  def match(other); end
  def original_headers; end
  def parse_cookies_from_header; end
  def self.[](*arg0); end
end
class Rack::MockRequest
  def delete(uri, opts = nil); end
  def get(uri, opts = nil); end
  def head(uri, opts = nil); end
  def initialize(app); end
  def options(uri, opts = nil); end
  def patch(uri, opts = nil); end
  def post(uri, opts = nil); end
  def put(uri, opts = nil); end
  def request(method = nil, uri = nil, opts = nil); end
  def self.env_for(uri = nil, opts = nil); end
  def self.parse_uri_rfc2396(uri); end
end
class Rack::MockRequest::FatalWarning < RuntimeError
end
class Rack::MockRequest::FatalWarner
  def flush; end
  def puts(warning); end
  def string; end
  def write(warning); end
end
