require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-rspec
inherit_gem:
  rubocop-shopify: rubocop.yml
AllCops:
    NewCops: enable
    Exclude:
      - integration_tests/minitest/grape_app/**/*
