# frozen_string_literal: true
source 'https://rubygems.org'
gem 'dotenv'
# api definitions
gem 'grape'
gem 'grape-entity'
gem 'grape-swagger'
# web server
gem 'puma'
# debugging
gem 'pry'
gem 'pg'
# task runner for ruby
gem 'rake'
gem 'flutter', path: '../../'

group :development, :test do
  gem 'minitest' #, require: false
  gem 'rack-test', require: 'rack/test'
end
