# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_40; end
module ::Anonymous_Delegator_41; end
module ::Anonymous_Delegator_44; end
module Grape::Extensions::ActiveSupport::Autoload; end
module T::CompatibilityPatches::RSpecCompatibility::MethodDoubleExtensions; end
module T::CompatibilityPatches::RSpecCompatibility::RecorderExtensions; end
